### ISSUE TITLE
RPC JSON API - listtransactions command

### ISSUE THREAD

**Issue by esejuli94** [Deviantcoin/Source#22]
I tried this command: `listtransactions` and I got this output: `[]`

I made two deposits and two withdrawals so I expect another output. What is the problem?

PD: I'm running your precompiled wallet on Windows Server 2016
PD2: I tried with this one: `listsinceblock` and I get the expected output but, what is the difference between those commands?

Thanks in advance.

**Comment by ScaMar** [comment]
on linux 
`deviant-cli -version`
`Deviant Core RPC client version v3.0.0.1-8e06493`
it works as expected (see below).
Such rpc call went from bitcoin core https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list
based on the definition above, list is blank for every account if there is only one transaction, otherwise the last should be shown
